[workspace]
resolver = "3"
members = ["crates/scry-core", "crates/scry-server", "crates/scry"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/Verdenroz/scry"

[workspace.dependencies]
scry-core = { path = "crates/scry-core" }
scry-server = { path = "crates/scry-server" }

[profile.release]
lto = "thin"
