//! Splits file content into retrieval chunks. Recognized languages get
//! tree-sitter definition-level chunks with symbol paths; everything else
//! falls back to blank-line-snapped windows. Line numbers are 1-based and
//! inclusive so hits print as `path:start-end`.

mod coalesce;
pub mod line_window;
mod treesitter;

pub use treesitter::Language;

const GENERATED_MARKER: &str = "@generated";
const GENERATED_HEAD_LINES: usize = 5;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Chunk {
    pub start_line: u32,
    pub end_line: u32,
    pub symbol: Option<String>,
    pub content: String,
}

/// Half-open line range `[start, end)` into a file, 0-based.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Span {
    pub start: usize,
    pub end: usize,
    pub symbol: Option<String>,
}

pub fn chunk_file(relpath: &str, content: &str) -> Vec<Chunk> {
    if content.contains('\0') || is_generated(content) {
        return Vec::new();
    }
    match Language::from_path(relpath) {
        Some(language) => {
            treesitter::chunk(language, content).unwrap_or_else(|| line_window::chunk(content))
        }
        None => line_window::chunk(content),
    }
}

/// The `@generated` header convention GitHub collapses diffs on; such
/// files duplicate their sources and crowd out hand-written code.
pub fn is_generated(content: &str) -> bool {
    content
        .lines()
        .take(GENERATED_HEAD_LINES)
        .any(|line| line.contains(GENERATED_MARKER))
}

pub(crate) fn lines_chunk(lines: &[&str], span: Span) -> Chunk {
    Chunk {
        start_line: span.start as u32 + 1,
        end_line: span.end as u32,
        content: lines[span.start..span.end].join("\n"),
        symbol: span.symbol,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_files_yield_no_chunks() {
        let source = "// @generated by `cargo soothfast docs gen-tests`\nfn main() {}\n";
        assert!(chunk_file("examples/gen.rs", source).is_empty());
        assert!(!chunk_file("src/lib.rs", "fn main() {}\n").is_empty());
    }

    #[test]
    fn generated_marker_only_counts_in_the_head() {
        let mut lines = vec!["fn main() {}"; 10];
        lines.push("// mentions @generated much later");
        assert!(!chunk_file("src/lib.rs", &lines.join("\n")).is_empty());
    }
}
